// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/aptimatic-landing/CenteredEditorial.tsx": () => import("../components/mockups/aptimatic-landing/CenteredEditorial.tsx"),
  "./components/mockups/aptimatic-landing/DenseGrid.tsx": () => import("../components/mockups/aptimatic-landing/DenseGrid.tsx"),
  "./components/mockups/aptimatic-landing/SplitHorizontal.tsx": () => import("../components/mockups/aptimatic-landing/SplitHorizontal.tsx")
};
